runtime: java21

env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  SPRING_PROFILES_ACTIVE: "prod"

inbound_services:
  - warmup